server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          url: https://github.com/js988174/MSA.git
          default-label: main

